// Core Workout Management Module - core/workout-core.js
// Barrel re-export file: imports from focused sub-modules and re-exports everything
// for backward compatibility with existing imports.

// === Workout Session Lifecycle ===
export {
    startWorkout,
    pauseWorkout,
    completeWorkout,
    cancelWorkout,
    cancelCurrentWorkout,
    continueInProgressWorkout,
    discardInProgressWorkout,
    discardEditedWorkout,
    editHistoricalWorkout,
    showWorkoutSelector,
    startWorkoutTimer,
    displayStaticDuration,
    updateWorkoutDuration,
    changeWorkoutLocation,
    selectWorkoutLocationOption,
    closeWorkoutLocationSelector,
    confirmWorkoutLocationChange,
    saveActiveWorkoutAsTemplate,
    toggleWorkoutOverflowMenu,
    closeWorkoutOverflowMenu,
    toggleWorkoutOverflow,
    closeWorkoutOverflow,
    updateWorkoutProgress,
    showWorkoutSummary,
    showMidWorkoutSummary,
} from './workout-session.js';

// === Exercise UI: Rendering, Set Management, Equipment, Video, Units ===
export {
    renderExercises,
    updateExerciseCard,
    createExerciseCard,
    generateExerciseTable,
    loadExerciseHistory,
    updateSet,
    addSet,
    deleteSet,
    addSetToExercise,
    removeSetFromExercise,
    saveExerciseNotes,
    markExerciseComplete,
    deleteExerciseFromWorkout,
    addExerciseToActiveWorkout,
    confirmExerciseAddToWorkout,
    changeExerciseEquipment,
    applyEquipmentChange,
    setGlobalUnit,
    setExerciseUnit,
    editExerciseDefaults,
    showExerciseVideo,
    hideExerciseVideo,
    showExerciseVideoAndToggleButton,
    hideExerciseVideoAndToggleButton,
    convertYouTubeUrl,
    loadLastWorkoutHint,
    toggleSetComplete,
    toggleReorderMode,
    toggleExerciseOverflow,
    supersetWithNext,
    ungroupExerciseFromWorkout,
    toggleExerciseExpansion,
    replaceExercise,
    updateCardioField,
    updateBodyweightSet,
} from './exercise-ui.js';

// === Rest Timer ===
export {
    toggleModalRestTimer,
    skipModalRestTimer,
    restoreModalRestTimer,
    saveActiveTimerState,
    restoreActiveTimerState,
    restoreTimerFromAppState,
    autoStartRestTimer,
    toggleHeaderRestTimer,
    skipHeaderRestTimer,
} from './rest-timer.js';

// === Active Workout V2 — Wizard UI ===
export {
    renderActiveWorkout,
    renderAll as renderActiveWorkoutAll,
    loadAutofillForAllExercises,
    awJumpTo,
    awNextExercise,
    awToggleSet,
    awUpdateSet,
    awAddSet,
    awRemoveSet,
    awSaveNotes,
    awAutoGrowNotes,
    awToggleExerciseMenu,
    awToggleWorkoutMenu,
    awCloseMenus,
    awDeleteExercise,
    awReplaceExercise,
    awConfirmExit,
    awCancelWorkout,
    awFinishWorkout,
    awUnlinkSuperset,
    awUnlinkSupersetGroup,
    awOpenJumpSheet,
    awOpenSupersetSheet,
    awToggleSupersetSelect,
    awConfirmSupersetLink,
    awOpenEquipmentSheet,
    awSelectEquipment,
    awAddExercise,
    awSetAddFilter,
    awSetAddSearch,
    awInsertExercise,
    awCloseSheet,
    awRestAdd30,
    awRestSkip,
    awEditRestDuration,
    awToggleUnit,
    awToggleReorder,
    awMoveExercise,
    awEndReorder,
    awEquipSearch,
    awQuickAddEquipment,
    awSaveNewEquipment,
    awDeleteEquipment,
} from './active-workout-ui.js';
